name: Fly Auto Deploy

on:
  push:
    branches: [ main ] # change branch as needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Fly
        uses: superfly/flyctl-actions@v1
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: "deploy --remote-only --config fly.toml"